APP := game
CC := g++ 
CCFLAGS := -g -Wall -pedantic
SFMLFLAGS := -lsfml-graphics -lsfml-window -lsfml-system 
TARGET := main

$(APP) : $(TARGET).cpp
	$(CC) $(TARGET).cpp -o $(TARGET).out $(CCFLAGS) $(SFMLFLAGS)


